### PR TITLE
Fix unused result

### LINKED ISSUE #11: Compilation failure error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
GCC version.
```
$ cc --version
cc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Errors.
```
$ make
mkdir -p /home/foobar/.estx
cp stx/* /home/foobar/.estx
mkdir -p bin/
cc main.c src/clipboard.c src/editor.c src/buffer.c src/util.c src/colors.c src/syntax.c -DSTXDIR=\"/home/foobar/.estx\" -o bin/e -Werror -Wall -g -fPIC -O2 -DNDEBUG -ftrapv -Wfloat-equal -Wundef -Wwrite-strings -Wuninitialized -pedantic -std=c11
src/editor.c: In function ‘e_die’:
src/editor.c:24:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(STDOUT_FILENO, "\x1b[2J\x1b[?47l\x1b""8", 12);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/editor.c: In function ‘e_exit’:
src/editor.c:31:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(STDOUT_FILENO, "\x1b[2J\x1b[?47l\x1b""8", 12);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/editor.c: In function ‘e_clear_screen’:
src/editor.c:214:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(STDOUT_FILENO, ab.b, ab.len);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/editor.c: In function ‘e_setup’:
src/editor.c:1214:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(STDOUT_FILENO, "\x1b""7\x1b[?47h", 8);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
src/syntax.c: In function ‘syntax_read_extensions’:
src/syntax.c:26:5: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
     fgets(line, MAX_LINE_WIDTH, f);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/syntax.c: In function ‘syntax_read_pattern’:
src/syntax.c:55:5: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
     fgets(line, MAX_LINE_WIDTH, f);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1
```

### PR DESCRIPTION
**Pull request by hellerve**
This PR fixes #11. It introduces the helper function `write_wrapped` to ignore warnings on certain versions of GCC/glibc and unused results.

### CODE REVIEW

File: src/editor.c [hunk 1]
```diff
@@ -20,15 +20,22 @@ void enable_raw_mode(e_context* ctx) {
 }
 
 
+/* sigh */
+void write_wrapped(int file, const char* str, int len) {
+   ssize_t x = write(file, str, len);
+   (void) x; 
+}
+
```
Comment (kianmeng) [inline src/editor.c:28]: Disclaimer: I'm not a C programmer in what so ever way. ;-) 
Wouldn't be nice to check for return value of `write` and name the function following your naming convention of `e_foobar`?

```
void e_write(int file, const char* str, int len) {
    if (write(file, str, len) != len) {
        fprintf(stderr, "Cannot write to file %i with error: %s\n", file, strerror(errno));
    }
}
```

Comment (hellerve) [reply src/editor.c:28]: I understand your concern here. A lot of the time in C we don’t do all of the error checking we could do because we assume that some calls never fail—in `e` I also don’t check for failures of `malloc`/`realloc` for instance. I’m also not so sure about `fprintf`ing the error here, especially after the last call to `write` failed and considering that the user could redirect stderr, leading to weird artifacts on the screen (in the best case).

As per the naming convention: the `e_<function>` convention is only really important for exported functions (as in, functions that are in the header) I feel, but I would agree that it’s less of a code smell to follow it regardless. I shall update it in the next commit.
